In [2]:
import numpy as np

In [55]:
a3 = np.array([[1,2,3], [4,5,6]])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a4 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a4.shape, a3.shape

((2, 3, 3), (3, 3))

In [12]:
a4.size, a3.size

(18, 9)

In [14]:
import pandas as pd

In [17]:
df = pd.DataFrame(a3)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Create Array

In [19]:
one = np.ones((3,3,3,), dtype = int)
one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
zeros = np.zeros((2,6), dtype = int)
zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [24]:
array_range = np.arange(2, 10, 1)
array_range

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
narray = np.arange(1,1)
narray

array([], dtype=int32)

In [31]:
random_array = np.random.random((2,3,2))
random_array

array([[[0.51416289, 0.00381153],
        [0.47029771, 0.16689947],
        [0.81056575, 0.56551019]],

       [[0.61534211, 0.15251229],
        [0.57823823, 0.36084905],
        [0.22904758, 0.73479911]]])

## Numpy Pseduo Random seed

In [33]:
seed_array = np.random.seed(1)
seed_array

## Manipulating array

### Airthmetic

In [132]:
a1 = np.array([1,2,3])

In [42]:
a2 = np.array([[4,5,6],[7,8,9]])

In [43]:
a1.shape, a2.shape

((3,), (2, 3))

In [44]:
a1 * a2

array([[ 4, 10, 18],
       [ 7, 16, 27]])

In [57]:
a3.reshape(3,3)
a3

ValueError: cannot reshape array of size 6 into shape (3,3)

In [46]:
a4*a3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [58]:
list1 = range(5) 
it = iter(list1)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
x

array([0., 1., 2., 3., 4.])

In [59]:
a = np.logspace(1,10,num = 10, base = 2) 
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [60]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
s = slice(2,7,2)
a[s]

array([2, 4, 6])

In [64]:
a[2:7:2]

array([2, 4, 6])

In [70]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

rows = np.array([[0,0],[3,3]])
rows
cols = np.array([[0,2],[0,2]]) 
cols
y = x[rows,cols] 
y

array([[ 0,  2],
       [ 9, 11]])

In [68]:
cols = np.array([[0,2],[0,2]]) 
cols

array([[0, 2],
       [0, 2]])

In [69]:
y = x[rows,cols] 
y

array([[ 0,  2],
       [ 9, 11]])

In [71]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
a4[:2, :1, :2]

array([[[ 1,  2]],

       [[10, 11]]])

In [80]:
a5 = np.random.randint(10, size=(2,2,2,5,6))
a5

array([[[[[3, 9, 2, 6, 2, 9],
          [1, 1, 5, 4, 8, 4],
          [7, 2, 3, 0, 5, 8],
          [2, 9, 4, 0, 0, 3],
          [4, 9, 6, 7, 6, 8]],

         [[0, 8, 0, 5, 2, 0],
          [8, 6, 1, 9, 5, 0],
          [0, 8, 1, 3, 7, 5],
          [1, 2, 6, 3, 2, 1],
          [8, 6, 5, 9, 1, 5]]],


        [[[1, 6, 3, 0, 5, 7],
          [3, 2, 9, 4, 4, 4],
          [9, 9, 9, 4, 8, 1],
          [6, 6, 7, 2, 4, 5],
          [7, 3, 7, 1, 6, 7]],

         [[9, 4, 8, 7, 0, 4],
          [1, 9, 7, 8, 6, 9],
          [1, 8, 3, 4, 7, 2],
          [2, 6, 1, 2, 2, 1],
          [5, 5, 2, 3, 3, 3]]]],



       [[[[0, 5, 3, 1, 0, 6],
          [4, 3, 1, 5, 5, 9],
          [0, 6, 7, 8, 2, 8],
          [5, 0, 8, 2, 8, 9],
          [4, 1, 2, 1, 6, 5]],

         [[0, 6, 1, 0, 1, 3],
          [5, 4, 7, 6, 4, 2],
          [9, 3, 2, 8, 4, 2],
          [5, 1, 2, 5, 3, 3],
          [3, 2, 8, 1, 9, 6]]],


        [[[4, 3, 4, 8, 3, 8],
          [7, 1, 3, 4, 0, 2],
          [3, 4, 2, 

In [83]:
a5[1,1,0,1,3]

4

In [99]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [101]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [103]:
a2*a4

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [112]:
a2_reshape = a2.reshape(2,2,3)
a2_reshape

ValueError: cannot reshape array of size 6 into shape (2,2,3)

In [110]:
a2_reshape

array([[[4, 5, 6],
        [7, 8, 9]]])

In [111]:
a2_reshape*a4

ValueError: operands could not be broadcast together with shapes (1,2,3) (2,3,3) 

### Aggregation 

## reshaping and transposing 


In [114]:
a2 

array([[4, 5, 6],
       [7, 8, 9]])

In [116]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [119]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [120]:
a2_reshape * a4

array([[[  4,   8,  12],
        [ 20,  25,  30],
        [ 42,  48,  54]],

       [[ 70,  77,  84],
        [104, 112, 120],
        [144, 153, 162]]])

### Element wise

In [121]:
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))
mat1

array([[1, 4, 9],
       [4, 0, 7],
       [7, 5, 4],
       [3, 7, 5],
       [0, 9, 7]])

In [122]:
mat2

array([[0, 8, 7],
       [7, 4, 1],
       [5, 0, 2],
       [3, 7, 7],
       [7, 0, 2]])

In [123]:
mat1 * mat2

array([[ 0, 32, 63],
       [28,  0,  7],
       [35,  0,  8],
       [ 9, 49, 35],
       [ 0,  0, 14]])

In [124]:
np.dot(mat1.mat2)

AttributeError: 'numpy.ndarray' object has no attribute 'mat2'

In [125]:
mat1.reshape(3,5)

array([[1, 4, 9, 4, 0],
       [7, 7, 5, 4, 3],
       [7, 5, 0, 9, 7]])

In [126]:
np.dot(mat1.reshape(3,5), mat2)

array([[ 85,  52,  57],
       [107, 112, 100],
       [111, 139, 131]])

#### comparision operator

In [133]:
a1

array([1, 2, 3])

In [128]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [136]:
a1<a2

array([[ True,  True,  True],
       [ True,  True,  True]])

# PANEL

In [137]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [138]:
firstP = pd.Panel(a4)
firstP

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 3 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 2
Minor_axis axis: 0 to 2